# Generated by Django 4.2.1 on 2023-08-16 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart',
            new_name='crt',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='product',
            new_name='prdt',
        ),
    ]
