# Generated by Django 4.2.1 on 2023-08-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_prdt_cartitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='crt',
            new_name='cart',
        ),
    ]
